name: 'Include Action'
description: 'Include snippets using c-style'
branding:
  color: blue
  icon: hash
inputs:
  input:
    description: 'The input file to process'
    required: true
  output:
    description: 'The file to write the output to'
    required: true
outputs:
  dockerfile:
    description: 'The generated Dockerfile contents'
  conclusion:
    description: 'Job conclusion'
  error:
    description: 'Error message'
runs:
  using: 'node12'
  main: 'index.js'